# config/juego.yaml
MUNDO:
  GRAVEDAD_X: 0.0
  GRAVEDAD_Y: 0.0
  TIEMPO_PASO_S: 0.016666
  ITERACIONES_VELOCIDAD: 8
  ITERACIONES_POSICION: 3

AUTOS:
  DEPORTIVO:
    VELOCIDAD_MAXIMA: 15.0
    ACELERACION: 1.0
    SALUD_BASE: 100
    MASA: 1.5
    CONTROL: 8.0